# Networks, learning and agreement
Different strategies read different evidence: measured contacts, co-expression, a trained model. Where they agree, a call is far more likely to be right -- and the self-tests say how much more.

In [1]:
from starplast import strategies as S
vote = S.run('layer_vote', target='compartment')
vote.tables['source weights']

               source    weight
0  measurements (kNN)  0.275040
1                xlms  0.121984
2        coexpression  0.115943
3              struct  0.074535
4              domain  0.051855
5       cotranslation  0.026790
6           cofitness  0.017404
7               ip_ms  0.003315
8          orthogroup  0.000000

In [2]:
clf = S.run('supervised_classifier', target='compartment')
clf.tables['what drives each class'].groupby('class').head(2).head(12)

             class                         measurement    weight
0   19S proteasome                n_crosslink_partners  1.393043
1   19S proteasome                    n_xlink_partners  1.285860
8     40S ribosome  mrna_log2_remaining_4h_actinomycin  1.156963
9     40S ribosome              ees_vs_tachyzoite_log2  0.819662
16    60S ribosome              fit_glucose_dependence  1.155662
17    60S ribosome                           codon_gc3  1.137740
24              ER                               is_tm  2.198795
25              ER                                n_tm  2.098841
32            ER 2       iron_depletion_protein_log2fc  1.759565
33            ER 2                  has_signal_peptide  1.677995
40           Golgi                               is_tm  1.854928
41           Golgi                                n_tm  1.795174

In [3]:
tri = S.test('triangulation', target='compartment')
tri

TestResult(strategy='triangulation', metric='precision of calls on hidden genes', observed=0.5385852090032154, null=[0.1592356687898089, 0.1580547112462006, 0.1536231884057971, 0.17352941176470588, 0.1407185628742515], min_effect=0.1, n_hidden=622, hidden='25% of the compartment labels, whole orthogroups at a time; 622 calls made on 951 hidden genes', null_kind='5 runs on shuffled labels', details=                        class  hidden  recovered    recall  called  precision
0              19S pr

In [4]:
{k: round(v, 3) for k, v in tri.numbers.items() if 'precision' in k}

{'measurements (kNN) precision': 0.406, 'classifier (logistic) precision': 0.461, 'networks (vote) precision': 0.286}

In [5]:
under = S.run('understudied_first', target='compartment')
under.tables['candidates'].head(10)

         gene_id                                        product           prediction   support  sources_agreeing
0  TGME49_225745                           hypothetical protein  nucleus - chromatin  0.546007               3.0
1  TGME49_266010           phosphatidylinositol 3- and 4-kinase  nucleus - chromatin  0.546007               3.0
2  TGME49_286270                           hypothetical protein  nucleus - chromatin  0.546007               3.0
3  TGME49_271145                           hypothetical protein  nucleus - chromatin  0.546007               3.0
4  TGME49_253870                           hypothetical protein           apicoplast  0.546007               3.0
5  TGME49_311625  bromodomain-containing protein BDP6, putative  nucleus - chromatin  0.546007               3.0
6  TGME49_270720                           hypothetical protein  nucleus - chromatin  0.546007               3.0
7  TGME49_225960                                     STE kinase  nucleus - chromatin  0.546007               3.0
8  TGME49_314875                                   RIC1 protein  nucleus - chromatin  0.546007               3.0
9  TGME49_273780                   SWI2/SNF2-containing protein  nucleus - chromatin  0.546007               3.0